### ISSUE TITLE
What's GSRN and who is responsible for it 

### ISSUE THREAD

**Issue by tomlankhorst** [hackerschoice/gsocket#38]
The documentation of gsocket often mentions GSRN. 

To me, this seems like the backbone of gsocket. However, the documentation doesn't provide information on what this service is, who manages it and why it can be hosted for free. A quick Google search also doesn't provide more info. 

How can users know that gsocket is safe and not, for example, a honeypot?

**Comment by SkyperTHC** [comment]
It’s not a honeypot because you can review the gsocket source and see that all traffic is encrypted (the gsrn only sees encrypted traffic).

the gsrn is currently being rewritten (in C) and will be released in the future. At the moment it’s a 209 line python script: it forwards packets between two tcp pipes.

**Comment by rootTHC** [comment]
Here is more:
https://www.gsocket.io/gsrn

**Comment by tomlankhorst** [comment]
Thanks a lot! Didn't come up in my Google searches yet so maybe it's just a matter of time.

**Comment by rootTHC** [comment]
> Thanks a lot! Didn't come up in my Google searches yet so maybe it's just a matter of time.

I only created the website after  you asked :> . Thanks for asking and reporting this.
