### ISSUE TITLE
openconnect example?

### ISSUE THREAD

**Issue by mrbluecoat** [hackerschoice/gsocket#46]
Will gsocket work with openconnect (ocserv)?

**Comment by rootTHC** [comment]
yes. I believe so. OpenConnect uses port 443 by default (TCP).

This is the closest example:
https://github.com/hackerschoice/gsocket/tree/master/examples/port-forward

Replace 6667 with 443 and it should work.

Please let me know if it works for you.

Otherwise please coin us on telegram channel to discuss: [https://t.me/thcorg](https://t.me/thcorg)
